# Generated by Django 4.0.5 on 2022-06-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_def',
            new_name='product_des',
        ),
    ]
