# Generated by Django 4.0.5 on 2022-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_products_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ImageField(upload_to='')),
                ('product_count', models.ImageField(upload_to='')),
                ('product_name', models.ManyToManyField(to='main_page.products')),
            ],
        ),
    ]
