# Generated by Django 4.0.5 on 2022-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_cart_product_name_cart_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_count',
            field=models.IntegerField(),
        ),
    ]
