# Generated by Django 4.0.5 on 2022-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_cart_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=70)),
                ('sale_percent', models.IntegerField()),
                ('sale_product', models.ManyToManyField(to='main_page.products')),
            ],
        ),
    ]
